# spring
# spring
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/girl?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: root

########################################## mybatis Info #####################################
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration.map-underscore-to-camel-case: true
  # 打印mybatis日志，生产环境请注释该配置
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# log info
logging:
  config: classpath:log4j2.xml


eureka:
  client:
    serviceUrl:
      # 注册中心，未增加用户认证
      # defaultZone: http://localhost:8761/eurekaServer/eureka/
      # 注册中心，增加用户认证
      defaultZone: http://darwindu:123456@localhost:8761/eurekaServer/eureka/
  instance:
    # 采用IP注册
    preferIpAddress: true
    # 定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    # 定义元数据
    metadataMap:
      username: darwindu
