# spring
spring:
  profiles:
    active: dev
# eureka注册中心，增加用户认证
  security:
    user:
      name: darwindu
      password: 123456


# log info
logging:
  config: classpath:log4j2.xml

# Eureka配置
eureka:
  server:
    # 自我保护关闭false，开启true，默认true
    enableSelfPreservation: true
  client:
    # 由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例, 它并不需要去检索服务, 所以也设置为 false，默认是true
    fetch-registry: false

