# spring
spring:
  profiles:
    active: dev
    # 定位模板的目录,给返回的页面添加后缀名
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cash: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/girl?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: root

# log info
logging:
  config: classpath:log4j2.xml

# security false不启用，true启用，默认true
#security:
#  basic:
#    enabled: false

